source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'JSchemaFormsExample' do
    #pod 'Eureka', :git => "https://github.com/xmartlabs/Eureka.git"
  pod 'JSchemaForms', :path => "../"
end

project 'JSchemaFormsExample.xcodeproj'
