source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'JSchemaFormExample' do
    #pod 'Eureka', :git => "https://github.com/xmartlabs/Eureka.git"
  pod 'JSchemaForm', :path => "../"
end

project 'JSchemaFormExample.xcodeproj'
